# Generated by Django 6.1.1 on 2026-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'bKash')], default=1),
        ),
    ]
