# Generated by Django 6.1.1 on 2026-09-28 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_lend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_date', models.DateField(blank=True, default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-borrow_date', '-created_at'],
                'indexes': [models.Index(fields=['borrow_date'], name='expense_bor_borrow__5ad305_idx')],
            },
        ),
    ]
